version: '3'

services:
  web:
    image: httpd:latest
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        tag: httpd.access
    networks:
      - efk
