version: '3'

services:
  logsource_driver:
    image: httpd:latest
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    networks:
      - efk
    depends_on:
      - fluentd
