version: '2.1'

services:
  logsource_driver:
    image: httpd:latest
    hostname: logsource_driver
    container_name: logsource_driver
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    networks:
      efk
    depends_on:
      - fluentd
