version: '2.1'

services:
  logsource_driver:
    container_name: logsource_driver
    depends_on:
      elasticsearch:
        condition: service_healthy
      fluentd:
        condition: service_healthy
    hostname: logsource_driver
    image: httpd:alpine
    links:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    networks:
      - efk
    ports:
      - "80:80"
