---
bootstrap:
  memory_lock: true
discovery:
  seed_hosts:
    - elasticsearch-master
    - elasticsearch-warm
cluster:
  initial_master_nodes:
    - master
  name: efk
logger:
  index:
    indexing:
      slowlog: "warn"
    search:
      slowlog: "warn"
network:
  host: 0.0.0.0
  publish_host: 0.0.0.0
node:
  name: "hot"
  master: false
  data: true
  ingest: false
  attr:
    box_type: hot
xpack:
  license:
    self_generated:
      type: trial
  monitoring:
    collection:
      enabled: true
  security:
    enabled: true
    audit:
      enabled: true
      logfile:
        events:
          emit_request_body: true
    http:
      ssl:
        certificate_authorities: /usr/share/elasticsearch/config/certificates/ca/ca.crt
        client_authentication: optional
        enabled: true
        keystore:
          path: /usr/share/elasticsearch/config/certificates/elasticsearch-hot/elasticsearch-hot.p12
    transport:
      ssl:
        certificate_authorities: /usr/share/elasticsearch/config/certificates/ca/ca.crt
        enabled: true
        verification_mode: certificate
        keystore:
          path: /usr/share/elasticsearch/config/certificates/elasticsearch-hot/elasticsearch-hot.p12
path:
  data: /usr/share/elasticsearch/data
  logs: /usr/share/elasticsearch/logs
