readonlyrest:
  ssl:
    # put the keystore in the same dir with elasticsearch.yml
#    keystore_file: "keystore.jks"
#    keystore_pass: readonlyrest
#    key_pass: readonlyrest
    allowed_protocols: [TLSv1.2]
    allowed_ciphers: [TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]

  response_if_req_forbidden: Forbidden by Readonly Rest!

  access_control_rules:
  - name: Accept all requests from localhost
    type: allow
    hosts: [127.0.0.1]
    verbosity: error

  - name: workaround
    type: allow
    actions:
      - "indices:data/read/field_caps*"
      - "indices:admin/template/put"
    verbosity: info

  - name: "::FLUENTD::"
    type: allow
    # auth_key is good for testing, but replace it with `auth_key_sha256`!
    # auth_key: fluentd:fluentd
    auth_key_sha256: 9545566c208f39b107b456430dd3b4b5b08eaa6c2abc62b2d6bcbb79c95b619c
    actions:
      - "cluster:monitor/main"
      - "indices:admin/types/exists"
      - "indices:data/read/*"
      - "indices:data/write/*"
      - "indices:admin/template/*"
      - "indices:admin/create"
    indices:
      - "agent-*"
      - "apache-*"
      - "bit-*"
      - "fluent-*"
      - "gem-*"
      - "k8s-*"
      - "kitchen-*"
      - "redis-*"
      - "unmatched-*"
    verbosity: error

  # We trust Kibana's server side process, full access granted via HTTP authentication
  - name: "::KIBANA::"
    type: allow
    # auth_key is good for testing, but replace it with `auth_key_sha256`!
    # auth_key: kibana:kibana
    auth_key_sha256: ab8aa94dd63debfa31ef8a9eae9582dcb252c06cdb6313e123546cc8edfeaf3e
    hosts: [kibana]
    kibana_access: admin
    verbosity: error # don't log successful request

  - name: "::ELASTICHQ::"
    type: allow
    # auth_key is good for testing, but replace it with `auth_key_sha256`!
    # auth_key: elastichq:elastichq
    auth_key_sha256: ccdff8600d84f900fe3419c286524788f8102581a40e591cd765ac724634bf15
    actions:
      - "cluster:monitor/*"
      - "indices:monitor/*"
    verbosity: error

  - name: "::TERMINAL::"
    type: allow
    # auth_key is good for testing, but replace it with `auth_key_sha256`!
    # auth_key: terminal:password
    auth_key_sha256: fc8d9571165e073ac292f6b42b2ff9d36b80a19e6396e1de30b0a83881cd4b2a
    actions:
      - "cluster:monitor/*"
    verbosity: error
