readonlyrest:
  ssl:
    # put the keystore in the same dir with elasticsearch.yml
#    keystore_file: "keystore.jks"
#    keystore_pass: readonlyrest
#    key_pass: readonlyrest
    allowed_protocols: [TLSv1.2]
    allowed_ciphers: [TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]

  access_control_rules:
  - name: "Block 0 - Allowing anything from localhost"
    type: allow

#  - name: "Block 1 - Allowing anything from localhost"
#    hosts: [127.0.0.1]
#
#  - name: "Block 2 - Other hosts can only read certain indices"
#    actions: ["indices:data/read/*"]
#    indices: ["logstash-*"] # aliases are taken in account!
#
