version: '2.1'

services:
  logsource_td_agent:
    build:
      context: ./via-td-agent
      args:
        VERSION_UBUNTU: $VERSION_UBUNTU
    command: java -Dlogger.loopCount=$LOGGER_LOOP_COUNT -Dlogger.sleep=$LOGGER_THREAD_SLEEP -cp /java-logger-$VERSION_JAVA_LOGGER.jar io.thinkstack.logger.slf4j.$LOGGER_ENTRY_POINT
    container_name: logsource_td_agent
    depends_on:
      elasticsearch:
        condition: service_healthy
      fluentd:
        condition: service_healthy
    env_file:
      - ./via-td-agent/ubuntu.properties
    hostname: logsource_td_agent
    networks:
      - efk
    ports:
      - "80:80"
    volumes:
      - ./via-td-agent/config/td-agent-simple.conf:/etc/td-agent/td-agent.conf
