version: '3'
services:
  logsource_td_agent:
    build:
      context: ./via-td-agent
      args:
        VERSION_UBUNTU: $VERSION_UBUNTU
    hostname: logsource_td_agent
    container_name: logsource_td_agent
    ports:
      - "80:80"
    links:
      - fluentd
    networks:
      - efk
