version: '2.1'

services:
  logsource_td_agent:
    build:
      context: ./via-td-agent
      args:
        VERSION_UBUNTU: $VERSION_UBUNTU
    container_name: logsource_td_agent
    depends_on:
      elasticsearch:
        condition: service_healthy
      fluentd:
        condition: service_healthy
    environment:
      FLUENTD_CONF: td-agent-simple.conf
      FLUENTD_AGGREGATOR_ADDR: fluentd
      FLUENTD_AGGREGATOR_PORT: 24224
      FLUENTD_SOURCE_PROJECT: logsource_td_agent
      FLUENTD_TAIL_TAG: via-td-agent
      VERSION_JAVA_LOGGER: $VERSION_JAVA_LOGGER
      LOGGER_LOOP_COUNT: $LOGGER_LOOP_COUNT
      LOGGER_THREAD_SLEEP: $LOGGER_THREAD_SLEEP
      LOGGER_ENTRY_POINT: $LOGGER_ENTRY_POINT
    hostname: logsource_td_agent
    networks:
      - efk
