version: '3'
services:
  logsource_td_agent:
    build:
      context: ./via-td-agent
      args:
        VERSION_UBUNTU: $VERSION_UBUNTU
    hostname: logsource_td_agent
    container_name: logsource_td_agent
    command: java -Dlogger.loopCount=$LOGGER_LOOP_COUNT -Dlogger.sleep=$LOGGER_THREAD_SLEEP -jar /java-logger.jar
    ports:
      - "80:80"
    links:
      - fluentd
    networks:
      - efk
