version: '2.1'

services:
  logsource:
    build:
      context: ./via-td-agent
      args:
        VERSION_UBUNTU: $VERSION_UBUNTU
    container_name: logsource
    depends_on:
      elasticsearch:
        condition: service_healthy
      fluentd:
        condition: service_healthy
    env_file:
      - ./via-td-agent/fluentd.properties
    hostname: logsource
    networks:
      - efk
    ports:
      - "9292:9292"
    volumes:
      - ./via-td-agent/config/:/etc/td-agent/
