version: '2.1'

services:
  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        VERSION_ELK: $VERSION_ELK
        FLAVOUR_ELK: $FLAVOUR_ELK
    container_name: elasticsearch
    env_file:
      - ./elasticsearch/elasticsearch.properties
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    hostname: elasticsearch
    networks:
      - efk
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/readonlyrest.yml:/usr/share/elasticsearch/config/readonlyrest.yml

  fluentd:
    build:
      context: ./fluentd
      args:
        VERSION_FLUENTD: $VERSION_FLUENTD
    container_name: fluentd
    depends_on:
      elasticsearch:
        condition: service_healthy
    env_file:
      - ./fluentd/fluentd.properties
    hostname: fluentd
    networks:
      - efk
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "5140:5140"
    volumes:
      - ./fluentd/config:/fluentd/etc
      - ./fluentd/certs:/fluentd/certs

  kibana:
    build:
      context: ./kibana
      args:
        VERSION_ELK: $VERSION_ELK
        FLAVOUR_ELK: $FLAVOUR_ELK
    container_name: kibana
    depends_on:
      fluentd:
        condition: service_healthy
    hostname: kibana
    networks:
      - efk
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
  efk:
    driver: bridge
