version: '3'

services:
  fluentd:
    build:
      context: ./fluentd
      args:
        VERSION_FLUENTD: $VERSION_FLUENTD
    hostname: fluentd
    container_name: fluentd
    env_file:
      - ./fluentd/fluentd.properties
    volumes:
      - ./fluentd/config:/fluentd/etc
      - ./fluentd/certs:/fluentd/certs
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - efk

  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        VERSION_ELK: $VERSION_ELK
        FLAVOUR_ELK: $FLAVOUR_ELK
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    env_file:
      - ./elasticsearch/elasticsearch.properties
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - efk
    depends_on:
      - fluentd
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    build:
      context: ./kibana
      args:
        VERSION_ELK: $VERSION_ELK
        FLAVOUR_ELK: $FLAVOUR_ELK
    hostname: kibana
    container_name: kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - efk
    depends_on:
      - elasticsearch

networks:
  efk:
    driver: bridge
