version: '3.6'

services:
  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        VERSION_EFK: ${VERSION_EFK}
    command: /usr/share/elasticsearch/custom-entrypoint.sh
    container_name: elasticsearch-master
    environment:
      - ${ES_JAVA_OPTS:-/dev/null}
      - KEY_PASSPHRASE=${KEY_PASSPHRASE}
      - CERTS_DIR=${CERTS_DIR}
    hostname: elasticsearch
    networks:
      - cluster
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - certs:$CERTS_DIR
      - elasticsearch_master:/usr/share/elasticsearch/data
      - ./elasticsearch/entrypoint.sh:/usr/share/elasticsearch/custom-entrypoint.sh
      - ./elasticsearch/config/master.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  elasticsearch-hot:
    build:
      context: ./elasticsearch
      args:
        VERSION_EFK: ${VERSION_EFK}
    command: /usr/share/elasticsearch/custom-entrypoint.sh
    container_name: elasticsearch-hot
    environment:
      - ${ES_JAVA_OPTS:-/dev/null}
      - KEY_PASSPHRASE=${KEY_PASSPHRASE}
    hostname: elasticsearch-hot
    networks:
      - cluster
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - certs:$CERTS_DIR
      - elasticsearch_hot:/usr/share/elasticsearch/data
      - ./elasticsearch/entrypoint.sh:/usr/share/elasticsearch/custom-entrypoint.sh
      - ./elasticsearch/config/hot.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  elasticsearch-warm:
    build:
      context: ./elasticsearch
      args:
        VERSION_EFK: ${VERSION_EFK}
    command: /usr/share/elasticsearch/custom-entrypoint.sh
    container_name: elasticsearch-warm
    environment:
      - ${ES_JAVA_OPTS:-/dev/null}
      - KEY_PASSPHRASE=${KEY_PASSPHRASE}
    hostname: elasticsearch-warm
    networks:
      - cluster
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - certs:$CERTS_DIR
      - elasticsearch_warm:/usr/share/elasticsearch/data
      - ./elasticsearch/entrypoint.sh:/usr/share/elasticsearch/custom-entrypoint.sh
      - ./elasticsearch/config/warm.yml:/usr/share/elasticsearch/config/elasticsearch.yml

#  fluentd:
#    build:
#      context: ./fluentd
#      args:
#        VERSION_FLUENTD: $VERSION_FLUENTD
#    container_name: fluentd
#    depends_on:
#      - elasticsearch
  #depends_on: {"es01.telemetry.internal": {"condition": "service_healthy"}}
#    env_file:
#      - ./fluentd/fluentd.properties
#    hostname: fluentd
#    networks:
#      - cluster
#    ports:
#      - "5140:5140"
#      - "5140:5140/udp"
#      - "24223:24223"
#      - "24223:24223/udp"
#      - "24224:24224"
#      - "24224:24224/udp"
#      - "24231:24231"
#      - "24231:24231/udp"
#    volumes:
#      - ./fluentd/config:/fluentd/etc
#      - ./fluentd/certs:/fluentd/certs

networks:
  cluster:
    driver: bridge

volumes:
  certs:
    driver: local
  elasticsearch_hot:
    driver: local
  elasticsearch_master:
    driver: local
  elasticsearch_warm:
    driver: local
