version: '3'

services:
  fluentd:
    build:
      context: ./fluentd
      args:
        FLUENTD_VERSION: $FLUENTD_VERSION
    hostname: fluentd
    env_file:
      - ./fluentd/fluentd.properties
    volumes:
      - ./fluentd/config:/fluentd/etc
      - ./fluentd/certs:/fluentd/certs
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - efk

  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
        ELK_FLAVOUR: $ELK_FLAVOUR
    hostname: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    env_file:
      - ./elasticsearch/elasticsearch.properties
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - efk
    depends_on:
      - fluentd
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    build:
      context: ./kibana
      args:
        ELK_VERSION: $ELK_VERSION
        ELK_FLAVOUR: $ELK_FLAVOUR
    hostname: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - efk
    depends_on:
      - elasticsearch

networks:
  efk:
    driver: bridge
