version: '2'
services:
  web:
    image: httpd:latest
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
