version: '2.1'

services:
  bit:
    build:
      context: ./via-td-agent-bit
      args:
        VERSION_CENTOS: $VERSION_CENTOS
    container_name: bit
    depends_on:
      elasticsearch:
        condition: service_healthy
      fluentd:
        condition: service_healthy
    env_file:
      - ./via-td-agent-bit/fluentd.properties
    hostname: bit
    networks:
      - efk
    volumes:
      - ./via-td-agent-bit/config/:/etc/td-agent-bit/
