version: '2.1'

services:
  nginx:
    build:
      context: ./nginx
      args:
        VERSION_NGINX: $VERSION_NGINX
    hostname: nginx
    container_name: nginx
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/config/htpasswd.users:/etc/nginx/htpasswd.users
    ports:
      - "8080:80"
    networks:
      - efk
    depends_on:
      - kibana
    restart:
      always
