version: '3.6'

services:
  elastichq:
    build:
      context: ./elasticHQ
    container_name: elastichq
    depends_on:
      - elasticsearch
    hostname: elastichq
    networks:
      - efk
    ports:
      - "5000:5000"
