version: '2.1'

services:
  elastichq:
    build:
      context: ./elasticHQ
    container_name: elastichq
    depends_on:
      elasticsearch:
        condition: service_healthy
    hostname: elastichq
    networks:
      - efk
    ports:
      - "5000:5000"
