---
server:
  name: kibana
  host: kibana
  port: 5601
  ssl:
    enabled: true
    certificate: /usr/share/kibana/config/certificates/kibana/kibana.crt
    key: /usr/share/kibana/config/certificates/kibana/kibana.key

elasticsearch:
  hosts:
    - https://elasticsearch:9200
  username: kibana
  ssl:
    verificationMode: certificate
    certificateAuthorities: /usr/share/kibana/config/certificates/ca/ca.crt

xpack:
  monitoring:
    elasticsearch:
      ssl:
        verificationMode: certificate
    ui:
      container:
        elasticsearch:
          enabled: true
