apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache
  namespace: logging
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: apache
        namespace: logging
    spec:
      containers:
      - image: httpd:latest
        imagePullPolicy: Always
        name: apache
        ports:
        - containerPort: 80
          name: apache
---
apiVersion: v1
kind: Service
metadata:
  namespace: logging
  name: apache
  labels:
    run: apache
spec:
  selector:
    run: apache
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
